version: '3.7'

services:
  web:
    build:
         dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 4000:8000
    env_file:
      - ./env/docker.env