# Generated by Django 4.1.7 on 2023-02-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="currency",
        ),
    ]
